interface Env {
  HQBOT_MODEL_ID: string;
  HQBOT_BOT_DAILY_BUDGET_USD: string;
  HQBOT_GLOBAL_DAILY_BUDGET_USD: string;
  HQBOT_TASK_BUDGET_USD: string;
  HQBOT_DAILY_TASK_LIMIT: string;
  HQBOT_SETUP_TOKEN: string;
}
